server:
  port: 8009
spring:
  profiles:
    active: dev


  application:
    name: ycl-gataway
eureka:
  instance:
    prefer-ip-address: true
    instance-id:
    hostname:

  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka

    ###该应用为注册中心
    register-with-eureka: true

    ###是否需要从eureka上获取注册信息
    fetch-registry: true

zuul:
  routes:
    api:
      path: /api/**
      serviceId:  ycl-comsumer